# Generated by Django 4.0.4 on 2022-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='value',
            field=models.IntegerField(default=''),
        ),
    ]
