# Generated by Django 4.0.4 on 2022-05-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_offer_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='value',
            new_name='pers',
        ),
    ]
